CONN / AS SYSDBA	
CREATE USER books_manager IDENTIFIED BY books_manager DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER books_manager QUOTA 100M ON USERS;
GRANT CONNECT TO books_manager;
GRANT CREATE TABLE TO books_manager;
GRANT CREATE VIEW TO books_manager;
GRANT CREATE SEQUENCE TO books_manager;
GRANT CREATE TRIGGER TO books_manager;
GRANT CREATE SYNONYM TO books_manager;
GRANT CREATE PROCEDURE TO books_manager;
disconnect;
