CONN / AS SYSDBA	
CREATE USER account_manager IDENTIFIED BY account_manager DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER account_manager QUOTA 100M ON USERS;
GRANT CONNECT TO account_manager;
GRANT CREATE TABLE TO account_manager;
GRANT CREATE VIEW TO account_manager;
GRANT CREATE SEQUENCE TO account_manager;
GRANT CREATE TRIGGER TO account_manager;
GRANT CREATE SYNONYM TO account_manager;
GRANT CREATE PROCEDURE TO account_manager;
disconnect;
