CONN / AS SYSDBA	
CREATE USER code_manager IDENTIFIED BY code_manager DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER code_manager QUOTA 100M ON USERS;
GRANT CONNECT TO code_manager;
GRANT CREATE TABLE TO code_manager;
GRANT CREATE VIEW TO code_manager;
GRANT CREATE SEQUENCE TO code_manager;
GRANT CREATE TRIGGER TO code_manager;
GRANT CREATE SYNONYM TO code_manager;
GRANT CREATE PROCEDURE TO code_manager;
disconnect;
